name = "evaluator"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
shellout = ">= 1.7.0 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
gleam_crypto = ">= 1.5.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
given = ">= 5.1.0 and < 6.0.0"
lustre = ">= 5.2.1 and < 6.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
choire = ">= 1.0.6 and < 2.0.0"
